export const caseData = [
  {
    imgUrl: "/images/cases/orekhovoEstate/orekhovoEstate.jpg",
    link: "orekhovoestate",
    title: "УСАДЬБА ОРЕХОВНО",
    text: "Первый европейский сад в России",
    width: "920px",
    pageData: [
      "/images/cases/orekhovoEstate/pagedata/0001.jpg",
      "/images/cases/orekhovoEstate/pagedata/0002.jpg",
      "/images/cases/orekhovoEstate/pagedata/0003.jpg",
      "/images/cases/orekhovoEstate/pagedata/0004.jpg",
      "/images/cases/orekhovoEstate/pagedata/0005.jpg",
      "/images/cases/orekhovoEstate/pagedata/0006.jpg",
      "/images/cases/orekhovoEstate/pagedata/0007.jpg",
      "/images/cases/orekhovoEstate/pagedata/0008.jpg",
      "/images/cases/orekhovoEstate/pagedata/0009.jpg",
      "/images/cases/orekhovoEstate/pagedata/0010.jpg",
      "/images/cases/orekhovoEstate/pagedata/0011.jpg",
      "/images/cases/orekhovoEstate/pagedata/0012.jpg",
      "/images/cases/orekhovoEstate/pagedata/0013.jpg",
      "/images/cases/orekhovoEstate/pagedata/0014.jpg",
    ],
  },
  {
    imgUrl: "/images/cases/7IlNature/7IlNature.jpg",
    link: "7ilnature",
    title: "7 IL NATURE",
    text: "Ландшафтная компания России",
    width: "640px",
    pageData: [
      "/images/cases/7IlNature/pagedata/0001.jpg",
      "/images/cases/7IlNature/pagedata/0002.jpg",
      "/images/cases/7IlNature/pagedata/0004.jpg",
      "/images/cases/7IlNature/pagedata/0005.jpg",
      "/images/cases/7IlNature/pagedata/0006.jpg",
      "/images/cases/7IlNature/pagedata/0007.jpg",
      "/images/cases/7IlNature/pagedata/0008.jpg",
      "/images/cases/7IlNature/pagedata/0009.jpg",
      "/images/cases/7IlNature/pagedata/0010.jpg",
      "/images/cases/7IlNature/pagedata/0011.jpg",
      "/images/cases/7IlNature/pagedata/0012.jpg",
      "/images/cases/7IlNature/pagedata/0013.jpg",
      "/images/cases/7IlNature/pagedata/0014.jpg",
    ],
  },
  {
    imgUrl: "/images/cases/ohmybalance/ohmybalance.jpg",
    link: "ohmybalance",
    title: "OH MY BALANCE",
    text: "Продукция здорового питания",
    width: "640px",
    pageData: [
      "/images/cases/ohmybalance/pagedata/0001.jpg",
      "/images/cases/ohmybalance/pagedata/0002.jpg",
      "/images/cases/ohmybalance/pagedata/0003.jpg",
      "/images/cases/ohmybalance/pagedata/0004.jpg",
    ],
  },
  {
    imgUrl: "/images/cases/googleads/googleads.jpg",
    link: "googleads",
    title: "Кейс - Google Ads для французского...",
    text: "Первый европейский сад в России",
    width: "920px",
    pageData: ["/images/cases/orekhovoEstate/orekhovoEstate.jpg"],
  },
  {
    imgUrl: "/images/cases/beautylabstore/beautylabstore.jpg",
    link: "beautylabstore",
    title: "BEAUTY LAB STORE",
    text: "САЛОН КРАСОТЫ И ИНТЕРНЕТ-МАГАЗИН КОСМЕТИКИ",
    width: "920px",
    pageData: ["/images/cases/orekhovoEstate/orekhovoEstate.jpg"],
  },
  {
    imgUrl: "/images/cases/contora/contora.jpg",
    link: "contora",
    title: "CONTORA",
    text: "САЛОН КРАСОТЫ ВЛАДИСЛАВА ЛИСОВЦА",
    width: "920px",
    pageData: ["/images/cases/orekhovoEstate/orekhovoEstate.jpg"],
  },
  {
    imgUrl: "/images/cases/crop&drpop/crop&drpop.jpg",
    link: "crop&drpop",
    title: "CROP&DROP",
    text: "КУЛЬТОВАЯ ПАРИКМАХЕРСКАЯ Санкт-...",
    width: "640px",
    pageData: ["/images/cases/orekhovoEstate/orekhovoEstate.jpg"],
  },
  {
    imgUrl: "/images/cases/eliseevsttore/eliseevsttore.jpg",
    link: "eliseevsttore",
    title: "ELISEEV STORE",
    text: "МАГАЗИН ОДЕЖДЫ",
    width: "920px",
    pageData: ["/images/cases/orekhovoEstate/orekhovoEstate.jpg"],
  },
  {
    imgUrl: "/images/cases/olgasysoeva/olgasysoeva.jpg",
    link: "olgasysoeva",
    title: "Зоопсихолог Ольга Сысоева",
    text: "Интернет-магазин вебинаров и книг",
    width: "920px",
    pageData: ["/images/cases/orekhovoEstate/orekhovoEstate.jpg"],
  },
  {
    imgUrl: "/images/cases/medicari/medicari.jpg",
    link: "medicari",
    title: "MEDICARI",
    text: "Центр здоровья",
    width: "640px",
    pageData: ["/images/cases/orekhovoEstate/orekhovoEstate.jpg"],
  },
];
