export const serviceData = [
  {
    title: "Комплексный маркетинг",
    text: "Синергия маркетинговых инструментов многократно увеличивает их эффективность для бизнеса",
    url: "/integratedMarketing",
    img: "./images/services/integratedMarketing/integratedMarketingMain.jpg",
  },
  {
    title: "SEO",
    text: "Оптимизируем сайт, улучшаем дизайни контент, чтобы привлечь рентабельных клиентов из поисковых систем",
    url: "/seo",
    img: "/images/services/seo/seoMain.jpg",
  },
  {
    title: "Брендинг",
    text: "Разрабатываем название и фирменный стиль бренда, которые нравятся аудитории, легко запоминаются и формируют ассоциативные образы.",
    url: "/branding",
    img: "/images/services/branding/brandingMain.jpg",
  },
  {
    title: "Маркетинговая стратегия",
    text: "Долгосрочное планирование развития вашего бренда и продукта. Определение наиболее рентабельных каналов продвижения и проектирование системы маркетинга.",
    url: "/marketingStrategy",
    img: "/images/services/marketingStrategy/marketingStrategyMain.jpg",
  },
  {
    title: "Разработка сайтов",
    text: "Делаем сайты, которые создают сильный образ бренда, доносят преимущества и вызывают желание купить",
    url: "/websites",
    img: "/images/services/websites/websitesMain.jpg",
  },
  {
    title: "Контент-маркетинг",
    text: "Формируем вокруг бренда аудиторию, которая будет рассказывать о вас и рекомендовать ваш продукт другим",
    url: "/contentMarketing",
    img: "/images/services/contentMarketing/contentMarketingMain.jpg",
  },
  {
    title: "Контент-стратегия",
    text: "Контент-стратегия — подготовительный этап перед контент-маркетингом",
    url: "/contentStrategy",
    img: "/images/services/contentMarketing/contentMarketingMain.jpg",
  },
  {
    title: "SMM",
    altTitle: "SMM продвижение",
    text: "Нацеленный на сильный бренд и продажи",
    url: "/smm",
    img: "/images/services/smm/smmMain.jpg",
  },
  {
    title: "Видеопродакшн",
    altTitle: "Фото- и видеопродакшн",
    text: "Усиливаем действие инструментов продвижения, повышаем узнаваемость и улучшаем репутацию бренда",
    url: "/videoProduction",
    img: "/images/services/videoProduction/videoProductionMain.jpg",
  },
  {
    title: "Контекстная реклама",
    text: "Поднимаем продажи, увеличиваем аудиторию вашего бренда и снижаем стоимость заявки",
    url: "/contextualAdvertising",
    img: "/images/services/contextualAdvertising/contextualAdvertisingMain.jpg",
  },
  {
    title: "Таргетированная реклама",
    text: "Увеличиваем продажи с помощью социальных сетей: создаем аудиторию бренда и формируем желание обратиться именно к вам",
    url: "/targetedAdvertising",
    img: "/images/services/targetedAdvertising/targetedAdvertisingMain.jpg",
  },
  {
    title: "Маркетинг продаж",
    text: "Увеличиваем конверсию из заявки в продажу и число повторных клиентов",
    url: "/salesMarketing",
    img: "/images/services/salesMarketing/salesMarketingMain.jpg",
  },
  {
    title: "Копирайтинг",
    text: "Разработаем уникальный текстовый стиль для вашего продукта и преобразуем социальные сети",
    url: "/copywriting",
    img: "/images/services/copywriting/copywritingMain.jpg",
  },
  {
    title: "Дизайн",
    text: "Разрабатываем запоминающийся дизайн бренда, который будет передавать настроение, стиль и ценности компании.",
    url: "/design",
    img: "/images/services/design/designMain.jpg",
  },
  {
    title: "Стратегия продвижения брендa",
    altTitle: "Бренд-стратегия",
    text: "Создание сильного и узнаваемого бренда при помощи разработки позиционирования, айдентики и стратегии продвижения.",
    url: "/brandPromotionStrategy",
    img: "/images/services/brandPromotionStrategy/brandPromotionStrategyMain.jpg",
  },
  {
    title: "Комплексное продвижение",
    text: "Чтобы продвижение приносило как можно больше прибыли, оно должно быть комплексным, измеримым и основываться на увеличении бизнес-показателей.",
    url: "/comprehensivePromotion",
    img: "/images/services/comprehensivePromotion/comprehensivePromotionMain.jpg",
  },
];
